stages:
  generate_data:
    cmd: python3 -m model.train.synth_data
    deps:
    - utils.py
    params:
    - model/params.yaml:
      - synth_data
    outs:
    - model/train/data/dataset:
        cache: false
  train:
    cmd: python3 -m model.train.train
    deps:
    - model/train/metrics.py

    params:
    - model/params.yaml:
      - seed
      - data_path
      - train
    outs:
    - model/train/trained_models/model_v1.pth:
        cache: false
